// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjmK9Ftn3JO3Wau2pH4SirJ78CNBN7qs',
    appId: '1:1029365171989:web:5acad019752238bad4cb1c',
    messagingSenderId: '1029365171989',
    projectId: 'jit-crm',
    authDomain: 'jit-crm.firebaseapp.com',
    storageBucket: 'jit-crm.appspot.com',
    measurementId: 'G-S322HECCNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWLqWc7rqh7IIlpuxGjD1mWmUZA8576A',
    appId: '1:1029365171989:android:0ca0e1ff1f2d3974d4cb1c',
    messagingSenderId: '1029365171989',
    projectId: 'jit-crm',
    storageBucket: 'jit-crm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi6oMCGpqLXG46dHJyLUpUfz-3vSO3tMo',
    appId: '1:1029365171989:ios:76fa61da21a262a7d4cb1c',
    messagingSenderId: '1029365171989',
    projectId: 'jit-crm',
    storageBucket: 'jit-crm.appspot.com',
    iosClientId: '1029365171989-cnkqju8r7j6focnp6scjq5pn8u48asbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi6oMCGpqLXG46dHJyLUpUfz-3vSO3tMo',
    appId: '1:1029365171989:ios:76fa61da21a262a7d4cb1c',
    messagingSenderId: '1029365171989',
    projectId: 'jit-crm',
    storageBucket: 'jit-crm.appspot.com',
    iosClientId: '1029365171989-cnkqju8r7j6focnp6scjq5pn8u48asbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cdms',
  );
}
